batch_size: 512
beta: 0.1
chunk: true
chunk_embedding_dim: 32
data_path: ./data
dataset: split_cifar100
gamma: 0.01
gold_model_path: ./weights/hnet/
gpu: 1
hnet_arch: layer_chunked_yaml
hnet_layers:
- 128
- 256
- 512
instruction_str: L1,L0,U1,L5,L8,L9,L7,U0,L2,L3,L4,U8,U3,U5,L6
lr: 0.001
mnet_arch: resnet
mnet_in_dim:
- 3
- 32
- 32
mnet_spec_path: specs
n_chunks: 200
n_epochs: 50
n_forget_epochs: 100
n_sampling: 10
n_tasks: 10
partial: false
resnet_type: 50
seed: 17
seq_name: 10a
task_embedding_dim: 32
ulr: 0.001
